language: rust

matrix:
  include:
    - rust: stable
    - rust: nightly
    - rust: 1.20.0

  script:
    - cd "${TRAVIS_BUILD_DIR}/type_level_values"
    - cargo build
    - cargo build --no-default-features
    - cargo test
    - cd "${TRAVIS_BUILD_DIR}/type_level_examples"
    - cargo build
