[workspace]
members = [
    "derive_type_level_lib",
    "derive_type_level",
    "type_level_examples",
    "type_level_values"
]


# to emit assembly 
#
# env RUSTFLAGS="--emit asm  --C codegen-units=1" cargo run --release --bin

# [profile.dev]
# codegen-units = 1