[package]
name = "type_level_tests"
version = "0.1.0"
authors = ["matias"]
workspace = "../"

[dependencies]

[build-dependencies]
derive_type_level_lib={path="../derive_type_level_lib"}
core_extensions={version="0.1"}